"""tests/test_generated_samples.py — committed generated-sample artifact integrity.

tests/generated_samples.json is regenerated by tools/gen_samples.py from the
verified bases in tools/gen_bases.py. These tests pin the artifact:
  1. it exists and is above the minimum volume
  2. regeneration reproduces it byte-for-byte (no stale edits)
  3. every sample stays faithful under the current validator (positives still
     trigger their target rule, negatives still produce zero violations)
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SAMPLES_PATH = ROOT / "tests" / "generated_samples.json"


def _load() -> dict:
    return json.loads(SAMPLES_PATH.read_text(encoding="utf-8"))


def test_generated_samples_file_exists():
    assert SAMPLES_PATH.is_file(), (
        "tests/generated_samples.json missing; run: py -3 tools/gen_samples.py"
    )


def test_generated_samples_min_total():
    data = _load()
    assert data["total"] >= 2000, "generated suite shrank below 2000 samples"
    assert len(data["samples"]) == data["total"]


def test_generated_samples_up_to_date():
    sys.path.insert(0, str(ROOT / "tools"))
    import gen_samples
    samples, _stats = gen_samples.generate()
    current = _load()["samples"]
    assert samples == current, (
        "tests/generated_samples.json is stale; run: py -3 tools/gen_samples.py"
    )


def test_generated_samples_all_faithful():
    from core.validator import Validator
    data = _load()
    validators: dict[str, Validator] = {}
    for i, s in enumerate(data["samples"]):
        lang = s["language"]
        v = validators.get(lang)
        if v is None:
            v = Validator(language=lang)
            validators[lang] = v
        r = v.validate(s["code"])
        rule_id = s["note"].split(":", 1)[0]
        if s["should_flag"]:
            fired = {x.rule_id for x in r.violations}
            assert rule_id in fired, (
                f"sample {i} ({s['note']}) expected to flag {rule_id}, fired {sorted(fired) or 'none'}"
            )
        else:
            assert not r.violations, (
                f"sample {i} ({s['note']}) must be clean, fired "
                f"{[x.rule_id for x in r.violations]}"
            )
